### ISSUE TITLE
Are you sure pipe mcmctree command works?

### ISSUE THREAD

**Issue by xiekunwhy** [kfuku52/nwkit#7]
Hi,

Are you sure the pipe mcmctree command works?
```
nwkit mcmctree \
--left_species Populus_trichocarpa \
--right_species Arabidopsis_thaliana \
--lower_bound 100 \
--upper_bound 120 \
--infile input.nwk \
| nwkit mcmctree \
--left_species Aquilegia_coerulea \
--right_species Arabidopsis_thaliana \
--lower_bound 130 \
--upper_bound 130 \
--add_header \
> output.nwk
```

when I use this pipe command line, I got following error

```
/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species Tribolium_castaneum --right_species Sitophilus_oryzae --lower_bound 152.3 --upper_bound 236.2 --infile Zmo.root.tree --lower_tailProb 1e-300 --upper_tailProb 1e-300|/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species Sitophilus_oryzae --right_species Anoplophora_glabripennis --lower_bound 154.0 --upper_bound 245.8
```

Number of leaves in input tree: 8
Traceback (most recent call last):
  File "/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit", line 267, in <module>
    args.handler(args)
  File "/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit", line 128, in command_mcmctree
    mcmctree_main(args)
  File "/Bio/User/kxie/software/mambaforge/envs/nwkit/lib/python3.11/site-packages/nwkit/mcmctree.py", line 192, in mcmctree_main
    tree = read_tree(args.infile, args.format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Bio/User/kxie/software/mambaforge/envs/nwkit/lib/python3.11/site-packages/nwkit/util.py", line 8, in read_tree
    tree = TreeNode(newick=nwk_string, format=format, quoted_node_names=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Bio/User/kxie/software/mambaforge/envs/nwkit/lib/python3.11/site-packages/ete3/coretype/tree.py", line 212, in __init__
    read_newick(newick, root_node = self, format=format,
  File "/Bio/User/kxie/software/mambaforge/envs/nwkit/lib/python3.11/site-packages/ete3/parser/newick.py", line 264, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
ete3.parser.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
You may want to check other newick loading flags like 'format' or 'quoted_node_names'.

Best,
Kun

**Comment by kfuku52** [comment]
I am not sure, without knowing the format of your input tree. Please try other `--format` options or send me your input tree.

**Comment by xiekunwhy** [comment]
Hi,

Here is the tree I used
```
((((agl,(cma,dvi)),sor),((tmo,zmo),tca)),ota);
```

save this tree in test.nwk file,

and the command line
```
/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species tca --right_species sor --lower_bound 152.3 --upper_bound 236.2- --infile test.nwk --lower_tailProb 1e-300 --upper_tailProb 1e-300 |/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species sor --right_species agl --lower_bound 154.0 --upper_bound 245.8
```
the first command line is normal, but the second command line not work.

Best,
Kun

**Comment by kfuku52** [comment]
I'm afraid that your input tree does not contain any of Tribolium_castaneum, Sitophilus_oryzae, and Anoplophora_glabripennis. Please match leaf labels with the specified species names.

**Comment by xiekunwhy** [comment]
I have change the sample name, you can try this command line, the error may reproduce
/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species tca --right_species sor --lower_bound 152.3 --upper_bound 236.2- --infile test.nwk --lower_tailProb 1e-300 --upper_tailProb 1e-300 |/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species sor --right_species agl --lower_bound 154.0 --upper_bound 245.8

**Comment by xiekunwhy** [comment]
/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species tca --right_species sor --lower_bound 152.3 --upper_bound 236.2- --infile test.nwk --lower_tailProb 1e-300 --upper_tailProb 1e-300 **is worked well.**

|/Bio/User/kxie/software/mambaforge/envs/nwkit/bin/nwkit mcmctree --left_species sor --right_species agl --lower_bound 154.0 --upper_bound 245.8 **not worked no matter how you change**  --format options

**Comment by kfuku52** [comment]
It worked well without error. Please double-check if you correctly specified the input file path. You might have specified an unexisting tree file, as the error message pointed out.


Command:
```
nwkit mcmctree --left_species tca --right_species sor --lower_bound 152.3 --upper_bound 236.2 --infile test.nwk --lower_tailProb 1e-300 --upper_tailProb 1e-300 \
| nwkit mcmctree --left_species sor --right_species agl --lower_bound 154.0 --upper_bound 245.8
```

Stdout:
```
((((agl,(cma,dvi)),sor)'B(154.0, 245.8, 0.025, 0.025)',((tmo,zmo),tca))'B(152.3, 236.2, 1e-300, 1e-300)',ota);
```

**Comment by kfuku52** [comment]
Also, "236.2-" is not a valid value. Please remove the hyphen.

**Comment by xiekunwhy** [comment]
still not work, when I copy your command line.
difference version of ete3 case this problem?

![image](https://github.com/kfuku52/nwkit/assets/17738229/788e9e20-22f0-4546-aa18-4209061e5f39)

**Comment by kfuku52** [comment]
That's unlikely but possible. Mine is:

```
# Name                    Version                   Build  Channel
ete3                      3.1.2              pyh9f0ad1d_0    conda-forge
```

Another possible source of error could be the shell environment, which may affect the pipe. If this is the case, you can separate the commands into two:
```
nwkit mcmctree --left_species tca --right_species sor --lower_bound 152.3 --upper_bound 236.2 --infile test.nwk --lower_tailProb 1e-300 --upper_tailProb 1e-300 --outfile tmp.nwk

nwkit mcmctree --left_species sor --right_species agl --lower_bound 154.0 --upper_bound 245.8 --infile tmp.nwk
```


If the version of ete3, or related dependency, causes this problem, changing `quoted_node_names` may solve the problem. I exposed this as a nwkit option `--quoted_node_names`. You can try this feature with nwkit 0.10.13.

**Comment by xiekunwhy** [comment]
Thank you very much, I will try it.

**Comment by kfuku52** [comment]
This issue has been closed due to inactivity. If the problem persists, please feel free to reopen it.
